server:
  port: 8081

spring:
  application:
    name: leandro.cahuana
  data:
    mongodb:
      database: nosql
      uri: mongodb+srv://leandroCahuana:9Zcm1M0gaJSWnuoa@cluster0.3s94j8f.mongodb.net/?appName=Cluster0

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html